"""correct type to boolean

Revision ID: 64facee4198d
Revises: c81fb8637cec
Create Date: 2025-03-22 23:20:47.745830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64facee4198d'
down_revision = 'c81fb8637cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('correct',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('correct',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
