"""correct column and annotation

Revision ID: c81fb8637cec
Revises: 
Create Date: 2025-03-22 23:15:44.391974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81fb8637cec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('annotation', sa.Text(), nullable=True))
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('annotation')
        batch_op.drop_column('correct')

    # ### end Alembic commands ###
